"""Prepare logic: plan eth-ape pin bumps and (optionally) open PRs."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from release_train.github import gh_available
from release_train.manifest import Manifest
from release_train.pins import MinorVersion, format_eth_ape_pin, rewrite_eth_ape_pin


@dataclass
class PreparePlanItem:
    repo: str
    repo_full: str
    new_pin: str
    branch: str
    pr_title: str
    notes: list[str]

    def gh_commands(self) -> list[str]:
        """Exact ``gh`` / git commands an operator can run (apply is partial in v1)."""
        return [
            f"# --- {self.repo_full} ---",
            f"gh repo clone {self.repo_full} /tmp/{self.repo} -- --depth 1",
            f"cd /tmp/{self.repo}",
            f"git checkout -b {self.branch}",
            f"# rewrite eth-ape pin in pyproject.toml -> {self.new_pin}",
            "# (use: release-train prepare --minor … with a local checkout helper, or edit)",
            "git add pyproject.toml",
            f'git commit -m "{self.pr_title}"',
            f"git push -u origin {self.branch}",
            f"gh pr create --repo {self.repo_full} --head {self.branch} "
            f"--title \"{self.pr_title}\" --body-file - <<'EOF'\n"
            f"{self._pr_body()}\nEOF",
        ]

    def _pr_body(self) -> str:
        lines = [
            "## Release train prepare",
            "",
            f"Bump `eth-ape` pin to `{self.new_pin}` for the upcoming minor.",
            "",
            "Auto-generated by `release-train prepare`.",
        ]
        if self.notes:
            lines.extend(["", "### Notes", *[f"- {n}" for n in self.notes]])
        return "\n".join(lines)


@dataclass
class PrepareResult:
    minor: MinorVersion
    items: list[PreparePlanItem]
    ape_reminder: str
    apply: bool
    apply_partial: bool = True  # v1: pin helpers + printed gh commands only


def plan_prepare(
    manifest: Manifest,
    minor: MinorVersion,
    *,
    apply: bool = False,
) -> PrepareResult:
    new_pin = format_eth_ape_pin(minor)
    branch = f"release-train/eth-ape-{minor.display()}"
    pr_title = f"chore: bump eth-ape pin for {minor.display()} train"
    items: list[PreparePlanItem] = []
    for plugin in manifest.plugins:
        items.append(
            PreparePlanItem(
                repo=plugin,
                repo_full=manifest.full_name(plugin),
                new_pin=new_pin,
                branch=branch,
                pr_title=pr_title,
                notes=[
                    f"Target pin: `{new_pin}`",
                    "Upper-bound policy: next minor (not `<1`).",
                ],
            )
        )

    ape_reminder = (
        f"Reminder: bump `fallback_version` in {manifest.full_name(manifest.core.repo)} "
        f"pyproject.toml (setuptools_scm) toward {minor.display()}.0 before cutting ape."
    )

    result = PrepareResult(
        minor=minor,
        items=items,
        ape_reminder=ape_reminder,
        apply=apply,
        apply_partial=True,
    )

    if apply:
        # v1: do not mutate remotes; surface exact commands + note TODOs
        pass

    return result


def rewrite_checkout_pin(pyproject_path: Path, minor: MinorVersion) -> tuple[str, int]:
    """Rewrite pins in a local pyproject.toml; returns (new_text, n). Writes the file."""
    original = pyproject_path.read_text(encoding="utf-8")
    new_text, n = rewrite_eth_ape_pin(original, minor)
    if n:
        pyproject_path.write_text(new_text, encoding="utf-8")
    return new_text, n


def format_prepare_report(result: PrepareResult) -> str:
    lines: list[str] = []
    mode = "APPLY (partial)" if result.apply else "DRY-RUN"
    lines.append(f"== prepare {result.minor.display()} [{mode}] ==")
    lines.append(result.ape_reminder)
    lines.append("")
    lines.append(f"Plugins to update: {len(result.items)}")
    lines.append(f"New pin: {format_eth_ape_pin(result.minor)}")
    lines.append("")
    for item in result.items:
        lines.append(f"  • {item.repo_full}")
        lines.append(f"      branch: {item.branch}")
        lines.append(f"      title:  {item.pr_title}")
        lines.append(f"      pin:    {item.new_pin}")
    lines.append("")
    if result.apply:
        lines.append("NOTE: prepare --apply is PARTIAL in v1.")
        lines.append("Pin rewrite helpers are implemented; remote PR creation is not automated.")
        lines.append("`gh` available: " + ("yes" if gh_available() else "no"))
        lines.append("")
        lines.append("Exact commands to run per repo:")
        lines.append("")
        for item in result.items:
            lines.extend(item.gh_commands())
            lines.append("")
    else:
        lines.append("Re-run with --apply to print executable gh/git command sequences.")
        lines.append("(Full automated PR open is a TODO for a later stage.)")
    return "\n".join(lines)
